print("RRRR ")
print("R   R")
print("R   R")
print("RRRR ")
print("R  R ")
print("R   R")
print("R   R")
print(" ")
print("IIIII")
print("  I  ")
print("  I  ")
print("  I  ")
print("  I  ")
print("  I  ")
print("IIIII")
print(" ")
print(" CCCC")
print("C    ")
print("C    ")
print("C    ")
print("C    ")
print("C    ")
print(" CCCC")
print(" ")
print("  A  ")
print(" A A ")
print("A   A")
print("AAAAA")
print("A   A")
print("A   A")
print("A   A")
print(" ")
print("RRRR ")
print("R   R")
print("R   R")
print("RRRR ")
print("R  R ")
print("R   R")
print("R   R")
print(" ")
print("DDDD ")
print("D   D")
print("D   D")
print("D   D")
print("D   D")
print("D   D")
print("DDDD ")
print(" ")
print(" OOO ")
print("O   O")
print("O   O")
print("O   O")
print("O   O")
print("O   O")
print(" OOO ")
print(" ")