print("_________")
print("|FFFFFFF/")
print("|F|      ")
print("|F|      ")
print("|FFFFF/  ")
print("|F|      ")
print("|F|      ")
print("|F| orce Calculator 3000")
print("---")
print("Copyright (C) Ricardo Olazabal. All rights reserved.")
print("")
mass = float(input("What is the mass in grams? ="))
acceleration = float(input("What is the acceleration in meters per second? ="))
def ForceCalc(m,a):
    force = float(m)*float(a)
    print("The force is "+str(force)+" Newtons.")
ForceCalc(mass,acceleration)